name: Pre-release Build (Personal)

on:
  workflow_dispatch: # Bu satır "Run workflow" butonunu getirecek!
  push:
    branches: [ master ] # Master branchine bir şey yüklendiğinde çalışacak

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Build Unsigned APK
      run: ./gradlew assembleDebug # Kendi kullanımın için hızlıca debug APK üretir
      env:
        SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
        SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cloudstream-firebase-build
        path: app/build/outputs/apk/debug/*.apk
